language: rust
branches:
  only:
  - master
  - dev
rust:
  - stable
  - nightly

addons:
  apt:
    packages:
    - zsh
    - bash
    - python3

env:
  global:
  - RUST_BACKTRACE=1

script:
- cargo build --verbose --examples
- cargo build --release # for integ tests
- cd tests && cargo test -v --features="$([ "${TRAVIS_RUST_VERSION}" == "nightly" ] && echo nightly || echo default)" -- --test-threads=1
