language: rust
branches:
  only:
  - master
  - dev
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - zsh

env:
  global:
  - RUST_BACKTRACE=1

script:
- cargo build --verbose --examples
- cargo build --release # for integ tests
- cd tests && cargo test -v
