sudo: required
language: rust
branches:
  only:
  - master
  - dev
rust:
  - stable
  - nightly

addons:
  apt:
    packages:
    - zsh
    - bash
    - python3
    - systemd

env:
  global:
  - RUST_BACKTRACE=1

script:
- head -n 9999 /boot/config-*
- cargo build --verbose --examples
- cargo build --release # for integ tests
- '[ ! -d /sys/fs/cgroup/unified ] && sudo mkdir -p /sys/fs/cgroup/unified && sudo mount -t cgroup2 none /sys/fs/cgroup/unified'
- cd tests && sudo -E $(which cargo) test -v --features="$([ "${TRAVIS_RUST_VERSION}" == "nightly" ] && echo nightly || echo default)"
