[package]
name = "pazi"
version = "0.0.1"
authors = ["Euan Kemp <euank@euank.com>"]

[dependencies]
clap = "~2"
rmp-serde = "~0.13"
serde = "~1"
serde_derive = "~1"
xdg = "~2"
libc = "~0.2"
env_logger = "~0.4"
log = "~0.3"
termion = "~1"
chan = "~0.1"
chan-signal = "~0.3"

tempdir = { version = "~0.3", optional = true }


[features]
default = [ ]
integ-tests = ["tempdir"]
