[package]
name = "pazi"
version = "0.0.1"
description = "A fast autojump helper"
authors = ["Euan Kemp <euank@euank.com>"]
homepage = "https://github.com/euank/pazi"
repository = "https://github.com/euank/pazi"
readme = "README.md"
keywords = ["autojump", "shell", "productivity-tool"]
license = "GPL-3.0"

[dependencies]
clap = "~2"
rmp-serde = "~0.13"
serde = "~1"
serde_derive = "~1"
xdg = "~2"
libc = "~0.2"
env_logger = "~0.4"
log = "~0.3"
termion = "~1"
chan = "~0.1"
chan-signal = "~0.3"

tempdir = { version = "~0.3", optional = true }
pty = { version = "~0.2", optional = true }
vte = { version = "~0.3", optional = true }


[features]
default = [ ]
integ-tests = [ "pty", "tempdir", "vte" ]
