[package]
name = "pazi"
version = "0.1.0"
authors = ["Euan Kemp <euank@euank.com>"]

[dependencies]
clap = "*"
rmp-serde = "*"
serde = "*"
serde_derive = "*"
xdg = "*"
libc = "*"
env_logger = "*"
log = "*"
termion = "*"
